DELETE  http://localhost:8080/events/1/register
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJleHAiOjE3MTEyMTY0NTEsInVzZXJJZCI6MX0.W4X5jGjhiFCvEohKbcg1TV54wRmwGccQ7WiqcqoyqXI