POST http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQHRlc3QuY29tIiwiZXhwIjoxNzExMjEzMjY3LCJ1c2VySWQiOjJ9.suLmF01n5YZgYBEGIk_cvzl59EO32kqTz7BI9JrjoeQ

{
  "Name":"test",
  "Description":"this is a test from user 2",
  "Location":"NewYork",
  "DateTime":"2024-01-02T15:04:05Z"
}