POST http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJleHAiOjE3MTEyMTY0NTEsInVzZXJJZCI6MX0.W4X5jGjhiFCvEohKbcg1TV54wRmwGccQ7WiqcqoyqXI

{
  "Name":"test",
  "Description":"this is a test from user 2",
  "Location":"NewYork",
  "DateTime":"2024-01-02T15:04:05Z"
}