DELETE  http://localhost:8080/events/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJleHAiOjE3MTEyMTQ4MTcsInVzZXJJZCI6MX0.SRIjf_JP-pITi3udz0yLy9EfBn7d6wcukBdTjjqHjJ4